### PR TITLE
Bugs and Issues ADR

### PR DESCRIPTION
**Pull request by geenalimfat**

### CODE REVIEW

**Review by HarshGurnani — APPROVED** [review]
Thanks for writing all this up, addresses all the bugs and looks great to me!

**Review by cdelira9 — APPROVED** [review]
looks great thank you geena!

**Review by sarveshmann — APPROVED** [review]
Thank you so much! Looks great and detailed.

**Review by jxnlee — COMMENTED** [review]
Thank you for putting it together! It's very nicely written!

**Review by jxnlee — APPROVED** [review]

**Review by Azathotha — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
