### PR TITLE
ADR Reorganization

### PR DESCRIPTION
**Pull request by HarshGurnani**
Moved tag color ADR to specs/adr folder and deleted admin/adr folder

### CODE REVIEW

**Review by cdelira9 — APPROVED** [review]
looks good thanks harsh!

**Review by dyc-github — APPROVED** [review]
Thank you!

**Review by symsoph — APPROVED** [review]
thank you harsh!

**Review by TerenceTan1021 — APPROVED** [review]
are we still allowed to edit the repo? Ill approve it if We are allowed

**Pull request merged**
