### PR TITLE
sprint and retrospective meeting notes

### PR DESCRIPTION
**Pull request by geenalimfat**

### CODE REVIEW

**Review by symsoph — APPROVED** [review]
i updated the attendance for one of the files. but thank you for the notes geena!

**Review by sarveshmann — APPROVED** [review]
I fixed the dates and numbering. Thank you Geena!

**Review by dyc-github — APPROVED** [review]
Everything looks good!

**Review by cdelira9 — APPROVED** [review]
looks great thank you geena!!

**Review by HarshGurnani — APPROVED** [review]
Thanks for taking notes!

**Pull request merged**
