### PR TITLE
JSDocs and Notes JSON ADR

### PR DESCRIPTION
**Pull request by kieraliz**
- Merge changes from JSDocs ADR (this was pushed to main branch but not deploy oops)
- Draft an ADR to specify the structure of JSON notes and other details

### CODE REVIEW

**Review by sarveshmann — APPROVED** [review]
Looks good! Just as a note: the current unit tests are based on sprint 1 note structure, so they will need to be modified accordingly. And, team 2 working on tags feature should also take the note structure into account.

**Review by cdelira9 — APPROVED** [review]
looks good

**Review by symsoph — APPROVED** [review]

**Review by HarshGurnani — COMMENTED** [review]
JSDocs ADR is very detailed - looks good to merge in!

**Review by HarshGurnani — APPROVED** [review]
JSDocs ADR is very detailed - looks good to merge in!

**Pull request merged**
