### PR TITLE
Electron compatibility refactor

### PR DESCRIPTION
**Pull request by dyc-github**
We have refactored the app to be less coupled and work with electron.js. We have additionally changed to a id system as opposed to trusting index to remain coonsistent. Finally there is an additional ADR outlining the motivations behind using electron and the design change.

### CODE REVIEW

**Review by geenalimfat — APPROVED** [review]
Looks good ty

**Review by symsoph — APPROVED** [review]
code looks well organized and has the jsdocs headers and such! thank you team 1!

**Review by HarshGurnani — APPROVED** [review]
Everything looks great and easy to read the code, lgtm!

**Review by sarveshmann — APPROVED** [review]
I was trying to test the functionality from team1-electron branch and I think the notes are not saving but I could be wrong. Anyway, we can fix it after merging if it's actually a problem.

**Pull request merged**
